### ISSUE TITLE
The video is not streaming

### ISSUE THREAD

**Issue by Fareed-Ahmad7** [AbdullahJanKhan/webrtc-android#1]
The audio is working fine. But video is not showing up. 
Tried to toggle video on&off button but didn't worked!
getting 0 frames from remote view and black screen on two devices 

<img width="1374" alt="Screenshot 2023-07-29 at 4 23 07 PM" src="https://github.com/AbdullahJanKhan/webrtc-android/assets/90202062/c7d34fb5-3c49-47b8-805d-98cfcf586e71">

![WhatsApp Image 2023-07-28 at 10 04 06 PM](https://github.com/AbdullahJanKhan/webrtc-android/assets/90202062/ed4ac61d-8fd0-474c-824c-c4c7a3d44996)

<img height="500" alt="phone" src="https://github.com/AbdullahJanKhan/webrtc-android/assets/90202062/9b523959-fef3-4bad-9262-00f812f5df42">

<img height="500" alt="phone1" src="https://github.com/AbdullahJanKhan/webrtc-android/assets/90202062/71b75b1b-6203-4f89-a907-f89c1a06c561">

**Comment by khalifarsm** [comment]
getting the same issue

**Comment by AbdullahJanKhan** [comment]
@khalifarsm @Fareed-Ahmad7 
Please take the new pull. This issue has been updated.
Thanks
